# Generated by Django 4.0.2 on 2022-02-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(default='/images/kohala-full-size-steel-string-acoustic-guitar.jpg', null=True, upload_to='images/'),
        ),
    ]
